// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserTrainingTrackingService.Infrastructure.Persistence.Data;

#nullable disable

namespace UserTrainingTrackingService.Migrations
{
    [DbContext(typeof(UserTrainingTrackingDbContext))]
    [Migration("20251111172311_AddBaseEntityToUserTrainingTrackingService")]
    partial class AddBaseEntityToUserTrainingTrackingService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserTrainingTrackingService.Domain.Entities.UserWorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("UserWorkoutSessions");
                });

            modelBuilder.Entity("UserTrainingTrackingService.Domain.Entities.WorkoutExerciseCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserWorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserWorkoutSessionId");

                    b.ToTable("WorkoutExerciseCompletions");
                });

            modelBuilder.Entity("UserTrainingTrackingService.Domain.Entities.WorkoutExerciseCompletion", b =>
                {
                    b.HasOne("UserTrainingTrackingService.Domain.Entities.UserWorkoutSession", "UserWorkoutSession")
                        .WithMany("CompletedExercises")
                        .HasForeignKey("UserWorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserWorkoutSession");
                });

            modelBuilder.Entity("UserTrainingTrackingService.Domain.Entities.UserWorkoutSession", b =>
                {
                    b.Navigation("CompletedExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
